// <auto-generated />
namespace GrocerCheckRebuild.Migrations.GrocerCheckRebuildMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedimagenamefrombrand : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedimagenamefrombrand));
        
        string IMigrationMetadata.Id
        {
            get { return "201605151731565_removed imagename from brand"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
